// flow-typed signature: 0156f68ea0975e09c3277da1e51892bf
// flow-typed version: <<STUB>>/filereader-stream_v^1.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'filereader-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'filereader-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'filereader-stream/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'filereader-stream/index' {
  declare module.exports: $Exports<'filereader-stream'>;
}
declare module 'filereader-stream/index.js' {
  declare module.exports: $Exports<'filereader-stream'>;
}
declare module 'filereader-stream/test.js' {
  declare module.exports: $Exports<'filereader-stream/test'>;
}
