// flow-typed signature: aa5e3adf4ccdc2c75dc3bcdf3801e30a
// flow-typed version: <<STUB>>/redux-fractal_v^1.7.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-fractal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-fractal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-fractal/dist/actions' {
  declare module.exports: any;
}

declare module 'redux-fractal/dist/index' {
  declare module.exports: any;
}

declare module 'redux-fractal/dist/local' {
  declare module.exports: any;
}

declare module 'redux-fractal/dist/localReducer' {
  declare module.exports: any;
}

declare module 'redux-fractal/dist/utils' {
  declare module.exports: any;
}

declare module 'redux-fractal/src/actions' {
  declare module.exports: any;
}

declare module 'redux-fractal/src/index' {
  declare module.exports: any;
}

declare module 'redux-fractal/src/local' {
  declare module.exports: any;
}

declare module 'redux-fractal/src/localReducer' {
  declare module.exports: any;
}

declare module 'redux-fractal/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-fractal/dist/actions.js' {
  declare module.exports: $Exports<'redux-fractal/dist/actions'>;
}
declare module 'redux-fractal/dist/index.js' {
  declare module.exports: $Exports<'redux-fractal/dist/index'>;
}
declare module 'redux-fractal/dist/local.js' {
  declare module.exports: $Exports<'redux-fractal/dist/local'>;
}
declare module 'redux-fractal/dist/localReducer.js' {
  declare module.exports: $Exports<'redux-fractal/dist/localReducer'>;
}
declare module 'redux-fractal/dist/utils.js' {
  declare module.exports: $Exports<'redux-fractal/dist/utils'>;
}
declare module 'redux-fractal/src/actions.js' {
  declare module.exports: $Exports<'redux-fractal/src/actions'>;
}
declare module 'redux-fractal/src/index.js' {
  declare module.exports: $Exports<'redux-fractal/src/index'>;
}
declare module 'redux-fractal/src/local.js' {
  declare module.exports: $Exports<'redux-fractal/src/local'>;
}
declare module 'redux-fractal/src/localReducer.js' {
  declare module.exports: $Exports<'redux-fractal/src/localReducer'>;
}
declare module 'redux-fractal/src/utils.js' {
  declare module.exports: $Exports<'redux-fractal/src/utils'>;
}
