// flow-typed signature: 53e806496fc18a29a5a9c23296a3e9ed
// flow-typed version: <<STUB>>/string-to-stream_v^1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-to-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-to-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string-to-stream/index' {
  declare module.exports: $Exports<'string-to-stream'>;
}
declare module 'string-to-stream/index.js' {
  declare module.exports: $Exports<'string-to-stream'>;
}
