// flow-typed signature: 8261412c98f0b9074d6a8fff25a952bd
// flow-typed version: <<STUB>>/opn_v^4.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'opn/index' {
  declare module.exports: $Exports<'opn'>;
}
declare module 'opn/index.js' {
  declare module.exports: $Exports<'opn'>;
}
