// flow-typed signature: 53d15d9c32d41244370c7d4a5204eb62
// flow-typed version: <<STUB>>/redux-little-router_v^12.1.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-little-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-little-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-little-router/demo/client/app' {
  declare module.exports: any;
}

declare module 'redux-little-router/demo/client/demo' {
  declare module.exports: any;
}

declare module 'redux-little-router/demo/client/routes' {
  declare module.exports: any;
}

declare module 'redux-little-router/demo/client/wrap' {
  declare module.exports: any;
}

declare module 'redux-little-router/demo/server/index' {
  declare module.exports: any;
}

declare module 'redux-little-router/dist/redux-little-router' {
  declare module.exports: any;
}

declare module 'redux-little-router/dist/redux-little-router.min' {
  declare module.exports: any;
}

declare module 'redux-little-router/interfaces/history' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/action-creators' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/action-types' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/browser-router' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/create-matcher' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/express-router' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/fragment' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/hapi-router' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/index' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/link' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/match-cache' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/provider' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/reducer-enhancer' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/store-enhancer' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/util/create-location' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/util/flatten-routes' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/util/generate-id' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/util/validate-routes' {
  declare module.exports: any;
}

declare module 'redux-little-router/lib/util/visit-children' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-little-router/demo/client/app.js' {
  declare module.exports: $Exports<'redux-little-router/demo/client/app'>;
}
declare module 'redux-little-router/demo/client/demo.js' {
  declare module.exports: $Exports<'redux-little-router/demo/client/demo'>;
}
declare module 'redux-little-router/demo/client/routes.js' {
  declare module.exports: $Exports<'redux-little-router/demo/client/routes'>;
}
declare module 'redux-little-router/demo/client/wrap.js' {
  declare module.exports: $Exports<'redux-little-router/demo/client/wrap'>;
}
declare module 'redux-little-router/demo/server/index.js' {
  declare module.exports: $Exports<'redux-little-router/demo/server/index'>;
}
declare module 'redux-little-router/dist/redux-little-router.js' {
  declare module.exports: $Exports<'redux-little-router/dist/redux-little-router'>;
}
declare module 'redux-little-router/dist/redux-little-router.min.js' {
  declare module.exports: $Exports<'redux-little-router/dist/redux-little-router.min'>;
}
declare module 'redux-little-router/interfaces/history.js' {
  declare module.exports: $Exports<'redux-little-router/interfaces/history'>;
}
declare module 'redux-little-router/lib/action-creators.js' {
  declare module.exports: $Exports<'redux-little-router/lib/action-creators'>;
}
declare module 'redux-little-router/lib/action-types.js' {
  declare module.exports: $Exports<'redux-little-router/lib/action-types'>;
}
declare module 'redux-little-router/lib/browser-router.js' {
  declare module.exports: $Exports<'redux-little-router/lib/browser-router'>;
}
declare module 'redux-little-router/lib/create-matcher.js' {
  declare module.exports: $Exports<'redux-little-router/lib/create-matcher'>;
}
declare module 'redux-little-router/lib/express-router.js' {
  declare module.exports: $Exports<'redux-little-router/lib/express-router'>;
}
declare module 'redux-little-router/lib/fragment.js' {
  declare module.exports: $Exports<'redux-little-router/lib/fragment'>;
}
declare module 'redux-little-router/lib/hapi-router.js' {
  declare module.exports: $Exports<'redux-little-router/lib/hapi-router'>;
}
declare module 'redux-little-router/lib/index.js' {
  declare module.exports: $Exports<'redux-little-router/lib/index'>;
}
declare module 'redux-little-router/lib/link.js' {
  declare module.exports: $Exports<'redux-little-router/lib/link'>;
}
declare module 'redux-little-router/lib/match-cache.js' {
  declare module.exports: $Exports<'redux-little-router/lib/match-cache'>;
}
declare module 'redux-little-router/lib/middleware.js' {
  declare module.exports: $Exports<'redux-little-router/lib/middleware'>;
}
declare module 'redux-little-router/lib/provider.js' {
  declare module.exports: $Exports<'redux-little-router/lib/provider'>;
}
declare module 'redux-little-router/lib/reducer-enhancer.js' {
  declare module.exports: $Exports<'redux-little-router/lib/reducer-enhancer'>;
}
declare module 'redux-little-router/lib/reducer.js' {
  declare module.exports: $Exports<'redux-little-router/lib/reducer'>;
}
declare module 'redux-little-router/lib/store-enhancer.js' {
  declare module.exports: $Exports<'redux-little-router/lib/store-enhancer'>;
}
declare module 'redux-little-router/lib/util/create-location.js' {
  declare module.exports: $Exports<'redux-little-router/lib/util/create-location'>;
}
declare module 'redux-little-router/lib/util/flatten-routes.js' {
  declare module.exports: $Exports<'redux-little-router/lib/util/flatten-routes'>;
}
declare module 'redux-little-router/lib/util/generate-id.js' {
  declare module.exports: $Exports<'redux-little-router/lib/util/generate-id'>;
}
declare module 'redux-little-router/lib/util/validate-routes.js' {
  declare module.exports: $Exports<'redux-little-router/lib/util/validate-routes'>;
}
declare module 'redux-little-router/lib/util/visit-children.js' {
  declare module.exports: $Exports<'redux-little-router/lib/util/visit-children'>;
}
