// flow-typed signature: 7db29b92ae885e2bfa64b9ff3cd7ec89
// flow-typed version: <<STUB>>/repa_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'repa/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'repa/main.js' {
  declare module.exports: $Exports<'repa/main'>;
}
