// flow-typed signature: c0ed00d1f03be302d01c998415b52819
// flow-typed version: <<STUB>>/vocabs-as_v^2.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vocabs-as'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vocabs-as' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vocabs-as/as' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vocabs-as/as.js' {
  declare module.exports: $Exports<'vocabs-as/as'>;
}
