// flow-typed signature: c1e1b550b090822e4913980c6df79266
// flow-typed version: <<STUB>>/is-observable_v*/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-observable/index' {
  declare module.exports: $Exports<'is-observable'>;
}
declare module 'is-observable/index.js' {
  declare module.exports: $Exports<'is-observable'>;
}
