// flow-typed signature: 576da233224a781f27254e6ee41efd8b
// flow-typed version: <<STUB>>/array-unique_v^0.3.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-unique'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-unique' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'array-unique/index' {
  declare module.exports: $Exports<'array-unique'>;
}
declare module 'array-unique/index.js' {
  declare module.exports: $Exports<'array-unique'>;
}
