// flow-typed signature: 35bfb1cf5c787f69718954fe8e6bf95f
// flow-typed version: <<STUB>>/babel-preset-node7_v^1.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-node7'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-node7' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-node7/index' {
  declare module.exports: $Exports<'babel-preset-node7'>;
}
declare module 'babel-preset-node7/index.js' {
  declare module.exports: $Exports<'babel-preset-node7'>;
}
