// flow-typed signature: d6c58d81fb23b160a5f40c52e8e47fd5
// flow-typed version: <<STUB>>/base64-stream_v^0.1.3/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base64-stream/lib/decode' {
  declare module.exports: any;
}

declare module 'base64-stream/lib/encode' {
  declare module.exports: any;
}

declare module 'base64-stream/test/decode.test' {
  declare module.exports: any;
}

declare module 'base64-stream/test/encode.test' {
  declare module.exports: any;
}

declare module 'base64-stream/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base64-stream/index' {
  declare module.exports: $Exports<'base64-stream'>;
}
declare module 'base64-stream/index.js' {
  declare module.exports: $Exports<'base64-stream'>;
}
declare module 'base64-stream/lib/decode.js' {
  declare module.exports: $Exports<'base64-stream/lib/decode'>;
}
declare module 'base64-stream/lib/encode.js' {
  declare module.exports: $Exports<'base64-stream/lib/encode'>;
}
declare module 'base64-stream/test/decode.test.js' {
  declare module.exports: $Exports<'base64-stream/test/decode.test'>;
}
declare module 'base64-stream/test/encode.test.js' {
  declare module.exports: $Exports<'base64-stream/test/encode.test'>;
}
declare module 'base64-stream/test/test.js' {
  declare module.exports: $Exports<'base64-stream/test/test'>;
}
