// flow-typed signature: 700a2d3eb61cef22517f6a678005b917
// flow-typed version: <<STUB>>/blob-to-stream_v^1.0.3/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blob-to-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blob-to-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blob-to-stream/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blob-to-stream/index' {
  declare module.exports: $Exports<'blob-to-stream'>;
}
declare module 'blob-to-stream/index.js' {
  declare module.exports: $Exports<'blob-to-stream'>;
}
declare module 'blob-to-stream/test/basic.js' {
  declare module.exports: $Exports<'blob-to-stream/test/basic'>;
}
