// flow-typed signature: ce262b44e095d9fae45ead9fed932fbf
// flow-typed version: <<STUB>>/cache-directory_v^1.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cache-directory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cache-directory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cache-directory/index' {
  declare module.exports: $Exports<'cache-directory'>;
}
declare module 'cache-directory/index.js' {
  declare module.exports: $Exports<'cache-directory'>;
}
