// flow-typed signature: beba847e15eef4e6b7ce53c1dadf6169
// flow-typed version: <<STUB>>/format-json_v^1.0.3/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'format-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'format-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'format-json/format-json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'format-json/format-json.js' {
  declare module.exports: $Exports<'format-json/format-json'>;
}
declare module 'format-json/index' {
  declare module.exports: $Exports<'format-json'>;
}
declare module 'format-json/index.js' {
  declare module.exports: $Exports<'format-json'>;
}
