// flow-typed signature: 1d7675d72b67008d327b3c2198923f78
// flow-typed version: <<STUB>>/googleapis_v^14.2.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'googleapis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'googleapis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'googleapis/apis/acceleratedmobilepageurl/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangebuyer/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangebuyer/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangebuyer/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangebuyer2/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangeseller/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangeseller/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adexchangeseller/v2.0' {
  declare module.exports: any;
}

declare module 'googleapis/apis/admin/datatransfer_v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/admin/directory_v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/admin/reports_v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adsense/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adsense/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/adsensehost/v4.1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/analytics/v2.4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/analytics/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/analyticsreporting/v4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/androidenterprise/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/androidpublisher/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/androidpublisher/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/androidpublisher/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/appengine/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/appengine/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/appengine/v1beta5' {
  declare module.exports: any;
}

declare module 'googleapis/apis/appsactivity/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/appstate/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/bigquery/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/blogger/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/blogger/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/books/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/calendar/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/civicinfo/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/classroom/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/cloudbilling/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/cloudbuild/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/clouddebugger/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/clouderrorreporting/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/cloudmonitoring/v2beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/cloudresourcemanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/cloudresourcemanager/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/cloudtrace/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/clouduseraccounts/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/apis/clouduseraccounts/beta' {
  declare module.exports: any;
}

declare module 'googleapis/apis/clouduseraccounts/vm_alpha' {
  declare module.exports: any;
}

declare module 'googleapis/apis/clouduseraccounts/vm_beta' {
  declare module.exports: any;
}

declare module 'googleapis/apis/compute/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/apis/compute/beta' {
  declare module.exports: any;
}

declare module 'googleapis/apis/compute/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/consumersurveys/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/container/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/content/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/content/v2sandbox' {
  declare module.exports: any;
}

declare module 'googleapis/apis/customsearch/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dataflow/v1b3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dataproc/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dataproc/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dataproc/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/datastore/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/datastore/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/datastore/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/datastore/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/deploymentmanager/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dfareporting/v2.4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dfareporting/v2.5' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dfareporting/v2.5beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dfareporting/v2.6' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dfareporting/v2.7' {
  declare module.exports: any;
}

declare module 'googleapis/apis/discovery/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dns/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/dns/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/doubleclickbidmanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/doubleclicksearch/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/drive/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/drive/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/firebasedynamiclinks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/firebaserules/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/fitness/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/fusiontables/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/fusiontables/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/games/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/gamesConfiguration/v1configuration' {
  declare module.exports: any;
}

declare module 'googleapis/apis/gamesManagement/v1management' {
  declare module.exports: any;
}

declare module 'googleapis/apis/genomics/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/genomics/v1alpha2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/genomics/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/gmail/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/groupsmigration/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/groupssettings/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/iam/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/identitytoolkit/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/kgsearch/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/language/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/licensing/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/logging/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/logging/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/manufacturers/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/mirror/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/ml/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/monitoring/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/oauth2/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/oauth2/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/pagespeedonline/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/pagespeedonline/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/partners/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/people/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/playmoviespartner/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/plus/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/plusDomains/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/prediction/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/prediction/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/prediction/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/prediction/v1.5' {
  declare module.exports: any;
}

declare module 'googleapis/apis/prediction/v1.6' {
  declare module.exports: any;
}

declare module 'googleapis/apis/proximitybeacon/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/pubsub/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/pubsub/v1beta1a' {
  declare module.exports: any;
}

declare module 'googleapis/apis/pubsub/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/qpxExpress/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/replicapool/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/replicapool/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/replicapoolupdater/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/reseller/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/resourceviews/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/resourceviews/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/runtimeconfig/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/runtimeconfig/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/safebrowsing/v4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/script/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/servicecontrol/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/servicemanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/sheets/v4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/siteVerification/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/slides/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/spectrum/v1explorer' {
  declare module.exports: any;
}

declare module 'googleapis/apis/speech/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/sqladmin/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/sqladmin/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/apis/storage/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/storage/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/storage/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/storagetransfer/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/surveys/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/tagmanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/taskqueue/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/taskqueue/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/tasks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/toolresults/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/translate/v2' {
  declare module.exports: any;
}

declare module 'googleapis/apis/urlshortener/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/vision/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/webfonts/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/webmasters/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/youtube/v3' {
  declare module.exports: any;
}

declare module 'googleapis/apis/youtubeAnalytics/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/youtubeAnalytics/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/apis/youtubereporting/v1' {
  declare module.exports: any;
}

declare module 'googleapis/lib/apirequest' {
  declare module.exports: any;
}

declare module 'googleapis/lib/auth/authclient' {
  declare module.exports: any;
}

declare module 'googleapis/lib/auth/computeclient' {
  declare module.exports: any;
}

declare module 'googleapis/lib/auth/jwtclient' {
  declare module.exports: any;
}

declare module 'googleapis/lib/auth/loginticket' {
  declare module.exports: any;
}

declare module 'googleapis/lib/auth/oauth2client' {
  declare module.exports: any;
}

declare module 'googleapis/lib/discovery' {
  declare module.exports: any;
}

declare module 'googleapis/lib/generator_utils' {
  declare module.exports: any;
}

declare module 'googleapis/lib/generator' {
  declare module.exports: any;
}

declare module 'googleapis/lib/googleapis' {
  declare module.exports: any;
}

declare module 'googleapis/lib/pemverifier' {
  declare module.exports: any;
}

declare module 'googleapis/lib/transporters' {
  declare module.exports: any;
}

declare module 'googleapis/lib/utils' {
  declare module.exports: any;
}

declare module 'googleapis/scripts/generate' {
  declare module.exports: any;
}

declare module 'googleapis/templates/api-endpoint' {
  declare module.exports: any;
}

declare module 'googleapis/templates/method-partial' {
  declare module.exports: any;
}

declare module 'googleapis/templates/resource-partial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'googleapis/apis/acceleratedmobilepageurl/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/acceleratedmobilepageurl/v1'>;
}
declare module 'googleapis/apis/adexchangebuyer/v1.2.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangebuyer/v1.2'>;
}
declare module 'googleapis/apis/adexchangebuyer/v1.3.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangebuyer/v1.3'>;
}
declare module 'googleapis/apis/adexchangebuyer/v1.4.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangebuyer/v1.4'>;
}
declare module 'googleapis/apis/adexchangebuyer2/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangebuyer2/v2beta1'>;
}
declare module 'googleapis/apis/adexchangeseller/v1.1.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangeseller/v1.1'>;
}
declare module 'googleapis/apis/adexchangeseller/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangeseller/v1'>;
}
declare module 'googleapis/apis/adexchangeseller/v2.0.js' {
  declare module.exports: $Exports<'googleapis/apis/adexchangeseller/v2.0'>;
}
declare module 'googleapis/apis/admin/datatransfer_v1.js' {
  declare module.exports: $Exports<'googleapis/apis/admin/datatransfer_v1'>;
}
declare module 'googleapis/apis/admin/directory_v1.js' {
  declare module.exports: $Exports<'googleapis/apis/admin/directory_v1'>;
}
declare module 'googleapis/apis/admin/reports_v1.js' {
  declare module.exports: $Exports<'googleapis/apis/admin/reports_v1'>;
}
declare module 'googleapis/apis/adsense/v1.3.js' {
  declare module.exports: $Exports<'googleapis/apis/adsense/v1.3'>;
}
declare module 'googleapis/apis/adsense/v1.4.js' {
  declare module.exports: $Exports<'googleapis/apis/adsense/v1.4'>;
}
declare module 'googleapis/apis/adsensehost/v4.1.js' {
  declare module.exports: $Exports<'googleapis/apis/adsensehost/v4.1'>;
}
declare module 'googleapis/apis/analytics/v2.4.js' {
  declare module.exports: $Exports<'googleapis/apis/analytics/v2.4'>;
}
declare module 'googleapis/apis/analytics/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/analytics/v3'>;
}
declare module 'googleapis/apis/analyticsreporting/v4.js' {
  declare module.exports: $Exports<'googleapis/apis/analyticsreporting/v4'>;
}
declare module 'googleapis/apis/androidenterprise/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/androidenterprise/v1'>;
}
declare module 'googleapis/apis/androidpublisher/v1.1.js' {
  declare module.exports: $Exports<'googleapis/apis/androidpublisher/v1.1'>;
}
declare module 'googleapis/apis/androidpublisher/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/androidpublisher/v1'>;
}
declare module 'googleapis/apis/androidpublisher/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/androidpublisher/v2'>;
}
declare module 'googleapis/apis/appengine/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/appengine/v1'>;
}
declare module 'googleapis/apis/appengine/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/apis/appengine/v1beta4'>;
}
declare module 'googleapis/apis/appengine/v1beta5.js' {
  declare module.exports: $Exports<'googleapis/apis/appengine/v1beta5'>;
}
declare module 'googleapis/apis/appsactivity/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/appsactivity/v1'>;
}
declare module 'googleapis/apis/appstate/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/appstate/v1'>;
}
declare module 'googleapis/apis/bigquery/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/bigquery/v2'>;
}
declare module 'googleapis/apis/blogger/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/blogger/v2'>;
}
declare module 'googleapis/apis/blogger/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/blogger/v3'>;
}
declare module 'googleapis/apis/books/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/books/v1'>;
}
declare module 'googleapis/apis/calendar/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/calendar/v3'>;
}
declare module 'googleapis/apis/civicinfo/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/civicinfo/v2'>;
}
declare module 'googleapis/apis/classroom/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/classroom/v1'>;
}
declare module 'googleapis/apis/cloudbilling/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/cloudbilling/v1'>;
}
declare module 'googleapis/apis/cloudbuild/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/cloudbuild/v1'>;
}
declare module 'googleapis/apis/clouddebugger/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/clouddebugger/v2'>;
}
declare module 'googleapis/apis/clouderrorreporting/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/clouderrorreporting/v1beta1'>;
}
declare module 'googleapis/apis/cloudmonitoring/v2beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/cloudmonitoring/v2beta2'>;
}
declare module 'googleapis/apis/cloudresourcemanager/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/cloudresourcemanager/v1'>;
}
declare module 'googleapis/apis/cloudresourcemanager/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/cloudresourcemanager/v1beta1'>;
}
declare module 'googleapis/apis/cloudtrace/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/cloudtrace/v1'>;
}
declare module 'googleapis/apis/clouduseraccounts/alpha.js' {
  declare module.exports: $Exports<'googleapis/apis/clouduseraccounts/alpha'>;
}
declare module 'googleapis/apis/clouduseraccounts/beta.js' {
  declare module.exports: $Exports<'googleapis/apis/clouduseraccounts/beta'>;
}
declare module 'googleapis/apis/clouduseraccounts/vm_alpha.js' {
  declare module.exports: $Exports<'googleapis/apis/clouduseraccounts/vm_alpha'>;
}
declare module 'googleapis/apis/clouduseraccounts/vm_beta.js' {
  declare module.exports: $Exports<'googleapis/apis/clouduseraccounts/vm_beta'>;
}
declare module 'googleapis/apis/compute/alpha.js' {
  declare module.exports: $Exports<'googleapis/apis/compute/alpha'>;
}
declare module 'googleapis/apis/compute/beta.js' {
  declare module.exports: $Exports<'googleapis/apis/compute/beta'>;
}
declare module 'googleapis/apis/compute/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/compute/v1'>;
}
declare module 'googleapis/apis/consumersurveys/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/consumersurveys/v2'>;
}
declare module 'googleapis/apis/container/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/container/v1'>;
}
declare module 'googleapis/apis/content/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/content/v2'>;
}
declare module 'googleapis/apis/content/v2sandbox.js' {
  declare module.exports: $Exports<'googleapis/apis/content/v2sandbox'>;
}
declare module 'googleapis/apis/customsearch/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/customsearch/v1'>;
}
declare module 'googleapis/apis/dataflow/v1b3.js' {
  declare module.exports: $Exports<'googleapis/apis/dataflow/v1b3'>;
}
declare module 'googleapis/apis/dataproc/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/dataproc/v1'>;
}
declare module 'googleapis/apis/dataproc/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/apis/dataproc/v1alpha1'>;
}
declare module 'googleapis/apis/dataproc/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/dataproc/v1beta1'>;
}
declare module 'googleapis/apis/datastore/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/datastore/v1'>;
}
declare module 'googleapis/apis/datastore/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/datastore/v1beta1'>;
}
declare module 'googleapis/apis/datastore/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/datastore/v1beta2'>;
}
declare module 'googleapis/apis/datastore/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/apis/datastore/v1beta3'>;
}
declare module 'googleapis/apis/deploymentmanager/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/deploymentmanager/v2'>;
}
declare module 'googleapis/apis/dfareporting/v2.4.js' {
  declare module.exports: $Exports<'googleapis/apis/dfareporting/v2.4'>;
}
declare module 'googleapis/apis/dfareporting/v2.5.js' {
  declare module.exports: $Exports<'googleapis/apis/dfareporting/v2.5'>;
}
declare module 'googleapis/apis/dfareporting/v2.5beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/dfareporting/v2.5beta1'>;
}
declare module 'googleapis/apis/dfareporting/v2.6.js' {
  declare module.exports: $Exports<'googleapis/apis/dfareporting/v2.6'>;
}
declare module 'googleapis/apis/dfareporting/v2.7.js' {
  declare module.exports: $Exports<'googleapis/apis/dfareporting/v2.7'>;
}
declare module 'googleapis/apis/discovery/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/discovery/v1'>;
}
declare module 'googleapis/apis/dns/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/dns/v1'>;
}
declare module 'googleapis/apis/dns/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/dns/v2beta1'>;
}
declare module 'googleapis/apis/doubleclickbidmanager/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/doubleclickbidmanager/v1'>;
}
declare module 'googleapis/apis/doubleclicksearch/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/doubleclicksearch/v2'>;
}
declare module 'googleapis/apis/drive/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/drive/v2'>;
}
declare module 'googleapis/apis/drive/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/drive/v3'>;
}
declare module 'googleapis/apis/firebasedynamiclinks/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/firebasedynamiclinks/v1'>;
}
declare module 'googleapis/apis/firebaserules/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/firebaserules/v1'>;
}
declare module 'googleapis/apis/fitness/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/fitness/v1'>;
}
declare module 'googleapis/apis/fusiontables/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/fusiontables/v1'>;
}
declare module 'googleapis/apis/fusiontables/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/fusiontables/v2'>;
}
declare module 'googleapis/apis/games/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/games/v1'>;
}
declare module 'googleapis/apis/gamesConfiguration/v1configuration.js' {
  declare module.exports: $Exports<'googleapis/apis/gamesConfiguration/v1configuration'>;
}
declare module 'googleapis/apis/gamesManagement/v1management.js' {
  declare module.exports: $Exports<'googleapis/apis/gamesManagement/v1management'>;
}
declare module 'googleapis/apis/genomics/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/genomics/v1'>;
}
declare module 'googleapis/apis/genomics/v1alpha2.js' {
  declare module.exports: $Exports<'googleapis/apis/genomics/v1alpha2'>;
}
declare module 'googleapis/apis/genomics/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/genomics/v1beta2'>;
}
declare module 'googleapis/apis/gmail/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/gmail/v1'>;
}
declare module 'googleapis/apis/groupsmigration/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/groupsmigration/v1'>;
}
declare module 'googleapis/apis/groupssettings/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/groupssettings/v1'>;
}
declare module 'googleapis/apis/iam/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/iam/v1'>;
}
declare module 'googleapis/apis/identitytoolkit/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/identitytoolkit/v3'>;
}
declare module 'googleapis/apis/kgsearch/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/kgsearch/v1'>;
}
declare module 'googleapis/apis/language/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/language/v1beta1'>;
}
declare module 'googleapis/apis/licensing/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/licensing/v1'>;
}
declare module 'googleapis/apis/logging/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/logging/v2'>;
}
declare module 'googleapis/apis/logging/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/logging/v2beta1'>;
}
declare module 'googleapis/apis/manufacturers/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/manufacturers/v1'>;
}
declare module 'googleapis/apis/mirror/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/mirror/v1'>;
}
declare module 'googleapis/apis/ml/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/ml/v1beta1'>;
}
declare module 'googleapis/apis/monitoring/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/monitoring/v3'>;
}
declare module 'googleapis/apis/oauth2/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/oauth2/v1'>;
}
declare module 'googleapis/apis/oauth2/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/oauth2/v2'>;
}
declare module 'googleapis/apis/pagespeedonline/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/pagespeedonline/v1'>;
}
declare module 'googleapis/apis/pagespeedonline/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/pagespeedonline/v2'>;
}
declare module 'googleapis/apis/partners/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/partners/v2'>;
}
declare module 'googleapis/apis/people/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/people/v1'>;
}
declare module 'googleapis/apis/playmoviespartner/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/playmoviespartner/v1'>;
}
declare module 'googleapis/apis/plus/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/plus/v1'>;
}
declare module 'googleapis/apis/plusDomains/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/plusDomains/v1'>;
}
declare module 'googleapis/apis/prediction/v1.2.js' {
  declare module.exports: $Exports<'googleapis/apis/prediction/v1.2'>;
}
declare module 'googleapis/apis/prediction/v1.3.js' {
  declare module.exports: $Exports<'googleapis/apis/prediction/v1.3'>;
}
declare module 'googleapis/apis/prediction/v1.4.js' {
  declare module.exports: $Exports<'googleapis/apis/prediction/v1.4'>;
}
declare module 'googleapis/apis/prediction/v1.5.js' {
  declare module.exports: $Exports<'googleapis/apis/prediction/v1.5'>;
}
declare module 'googleapis/apis/prediction/v1.6.js' {
  declare module.exports: $Exports<'googleapis/apis/prediction/v1.6'>;
}
declare module 'googleapis/apis/proximitybeacon/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/proximitybeacon/v1beta1'>;
}
declare module 'googleapis/apis/pubsub/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/pubsub/v1'>;
}
declare module 'googleapis/apis/pubsub/v1beta1a.js' {
  declare module.exports: $Exports<'googleapis/apis/pubsub/v1beta1a'>;
}
declare module 'googleapis/apis/pubsub/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/pubsub/v1beta2'>;
}
declare module 'googleapis/apis/qpxExpress/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/qpxExpress/v1'>;
}
declare module 'googleapis/apis/replicapool/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/replicapool/v1beta1'>;
}
declare module 'googleapis/apis/replicapool/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/replicapool/v1beta2'>;
}
declare module 'googleapis/apis/replicapoolupdater/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/replicapoolupdater/v1beta1'>;
}
declare module 'googleapis/apis/reseller/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/reseller/v1'>;
}
declare module 'googleapis/apis/resourceviews/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/resourceviews/v1beta1'>;
}
declare module 'googleapis/apis/resourceviews/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/resourceviews/v1beta2'>;
}
declare module 'googleapis/apis/runtimeconfig/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/runtimeconfig/v1'>;
}
declare module 'googleapis/apis/runtimeconfig/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/runtimeconfig/v1beta1'>;
}
declare module 'googleapis/apis/safebrowsing/v4.js' {
  declare module.exports: $Exports<'googleapis/apis/safebrowsing/v4'>;
}
declare module 'googleapis/apis/script/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/script/v1'>;
}
declare module 'googleapis/apis/servicecontrol/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/servicecontrol/v1'>;
}
declare module 'googleapis/apis/servicemanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/servicemanagement/v1'>;
}
declare module 'googleapis/apis/sheets/v4.js' {
  declare module.exports: $Exports<'googleapis/apis/sheets/v4'>;
}
declare module 'googleapis/apis/siteVerification/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/siteVerification/v1'>;
}
declare module 'googleapis/apis/slides/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/slides/v1'>;
}
declare module 'googleapis/apis/spectrum/v1explorer.js' {
  declare module.exports: $Exports<'googleapis/apis/spectrum/v1explorer'>;
}
declare module 'googleapis/apis/speech/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/speech/v1beta1'>;
}
declare module 'googleapis/apis/sqladmin/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/apis/sqladmin/v1beta3'>;
}
declare module 'googleapis/apis/sqladmin/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/apis/sqladmin/v1beta4'>;
}
declare module 'googleapis/apis/storage/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/storage/v1'>;
}
declare module 'googleapis/apis/storage/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/storage/v1beta1'>;
}
declare module 'googleapis/apis/storage/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/storage/v1beta2'>;
}
declare module 'googleapis/apis/storagetransfer/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/storagetransfer/v1'>;
}
declare module 'googleapis/apis/surveys/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/surveys/v2'>;
}
declare module 'googleapis/apis/tagmanager/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/tagmanager/v1'>;
}
declare module 'googleapis/apis/taskqueue/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/taskqueue/v1beta1'>;
}
declare module 'googleapis/apis/taskqueue/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/apis/taskqueue/v1beta2'>;
}
declare module 'googleapis/apis/tasks/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/tasks/v1'>;
}
declare module 'googleapis/apis/toolresults/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/apis/toolresults/v1beta3'>;
}
declare module 'googleapis/apis/translate/v2.js' {
  declare module.exports: $Exports<'googleapis/apis/translate/v2'>;
}
declare module 'googleapis/apis/urlshortener/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/urlshortener/v1'>;
}
declare module 'googleapis/apis/vision/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/vision/v1'>;
}
declare module 'googleapis/apis/webfonts/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/webfonts/v1'>;
}
declare module 'googleapis/apis/webmasters/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/webmasters/v3'>;
}
declare module 'googleapis/apis/youtube/v3.js' {
  declare module.exports: $Exports<'googleapis/apis/youtube/v3'>;
}
declare module 'googleapis/apis/youtubeAnalytics/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/youtubeAnalytics/v1'>;
}
declare module 'googleapis/apis/youtubeAnalytics/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/apis/youtubeAnalytics/v1beta1'>;
}
declare module 'googleapis/apis/youtubereporting/v1.js' {
  declare module.exports: $Exports<'googleapis/apis/youtubereporting/v1'>;
}
declare module 'googleapis/lib/apirequest.js' {
  declare module.exports: $Exports<'googleapis/lib/apirequest'>;
}
declare module 'googleapis/lib/auth/authclient.js' {
  declare module.exports: $Exports<'googleapis/lib/auth/authclient'>;
}
declare module 'googleapis/lib/auth/computeclient.js' {
  declare module.exports: $Exports<'googleapis/lib/auth/computeclient'>;
}
declare module 'googleapis/lib/auth/jwtclient.js' {
  declare module.exports: $Exports<'googleapis/lib/auth/jwtclient'>;
}
declare module 'googleapis/lib/auth/loginticket.js' {
  declare module.exports: $Exports<'googleapis/lib/auth/loginticket'>;
}
declare module 'googleapis/lib/auth/oauth2client.js' {
  declare module.exports: $Exports<'googleapis/lib/auth/oauth2client'>;
}
declare module 'googleapis/lib/discovery.js' {
  declare module.exports: $Exports<'googleapis/lib/discovery'>;
}
declare module 'googleapis/lib/generator_utils.js' {
  declare module.exports: $Exports<'googleapis/lib/generator_utils'>;
}
declare module 'googleapis/lib/generator.js' {
  declare module.exports: $Exports<'googleapis/lib/generator'>;
}
declare module 'googleapis/lib/googleapis.js' {
  declare module.exports: $Exports<'googleapis/lib/googleapis'>;
}
declare module 'googleapis/lib/pemverifier.js' {
  declare module.exports: $Exports<'googleapis/lib/pemverifier'>;
}
declare module 'googleapis/lib/transporters.js' {
  declare module.exports: $Exports<'googleapis/lib/transporters'>;
}
declare module 'googleapis/lib/utils.js' {
  declare module.exports: $Exports<'googleapis/lib/utils'>;
}
declare module 'googleapis/scripts/generate.js' {
  declare module.exports: $Exports<'googleapis/scripts/generate'>;
}
declare module 'googleapis/templates/api-endpoint.js' {
  declare module.exports: $Exports<'googleapis/templates/api-endpoint'>;
}
declare module 'googleapis/templates/method-partial.js' {
  declare module.exports: $Exports<'googleapis/templates/method-partial'>;
}
declare module 'googleapis/templates/resource-partial.js' {
  declare module.exports: $Exports<'googleapis/templates/resource-partial'>;
}
