// flow-typed signature: 24a173a0214171b88b1d642f5bddd66a
// flow-typed version: <<STUB>>/imap_v^0.8.18/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imap/deps/encoding/encoding-indexes' {
  declare module.exports: any;
}

declare module 'imap/deps/encoding/encoding' {
  declare module.exports: any;
}

declare module 'imap/lib/Connection' {
  declare module.exports: any;
}

declare module 'imap/lib/Parser' {
  declare module.exports: any;
}

declare module 'imap/test/test-connection-fetch-dup' {
  declare module.exports: any;
}

declare module 'imap/test/test-connection-fetch-frag' {
  declare module.exports: any;
}

declare module 'imap/test/test-connection-fetch-spillover' {
  declare module.exports: any;
}

declare module 'imap/test/test-connection-fetch-stringbody' {
  declare module.exports: any;
}

declare module 'imap/test/test-connection-idle-normal' {
  declare module.exports: any;
}

declare module 'imap/test/test-connection-idle-order' {
  declare module.exports: any;
}

declare module 'imap/test/test-parse-bodystructure' {
  declare module.exports: any;
}

declare module 'imap/test/test-parse-envelope-addrs' {
  declare module.exports: any;
}

declare module 'imap/test/test-parse-expr' {
  declare module.exports: any;
}

declare module 'imap/test/test-parse-header' {
  declare module.exports: any;
}

declare module 'imap/test/test-parser' {
  declare module.exports: any;
}

declare module 'imap/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imap/deps/encoding/encoding-indexes.js' {
  declare module.exports: $Exports<'imap/deps/encoding/encoding-indexes'>;
}
declare module 'imap/deps/encoding/encoding.js' {
  declare module.exports: $Exports<'imap/deps/encoding/encoding'>;
}
declare module 'imap/lib/Connection.js' {
  declare module.exports: $Exports<'imap/lib/Connection'>;
}
declare module 'imap/lib/Parser.js' {
  declare module.exports: $Exports<'imap/lib/Parser'>;
}
declare module 'imap/test/test-connection-fetch-dup.js' {
  declare module.exports: $Exports<'imap/test/test-connection-fetch-dup'>;
}
declare module 'imap/test/test-connection-fetch-frag.js' {
  declare module.exports: $Exports<'imap/test/test-connection-fetch-frag'>;
}
declare module 'imap/test/test-connection-fetch-spillover.js' {
  declare module.exports: $Exports<'imap/test/test-connection-fetch-spillover'>;
}
declare module 'imap/test/test-connection-fetch-stringbody.js' {
  declare module.exports: $Exports<'imap/test/test-connection-fetch-stringbody'>;
}
declare module 'imap/test/test-connection-idle-normal.js' {
  declare module.exports: $Exports<'imap/test/test-connection-idle-normal'>;
}
declare module 'imap/test/test-connection-idle-order.js' {
  declare module.exports: $Exports<'imap/test/test-connection-idle-order'>;
}
declare module 'imap/test/test-parse-bodystructure.js' {
  declare module.exports: $Exports<'imap/test/test-parse-bodystructure'>;
}
declare module 'imap/test/test-parse-envelope-addrs.js' {
  declare module.exports: $Exports<'imap/test/test-parse-envelope-addrs'>;
}
declare module 'imap/test/test-parse-expr.js' {
  declare module.exports: $Exports<'imap/test/test-parse-expr'>;
}
declare module 'imap/test/test-parse-header.js' {
  declare module.exports: $Exports<'imap/test/test-parse-header'>;
}
declare module 'imap/test/test-parser.js' {
  declare module.exports: $Exports<'imap/test/test-parser'>;
}
declare module 'imap/test/test.js' {
  declare module.exports: $Exports<'imap/test/test'>;
}
