// flow-typed signature: 3b73a290577dd682fe9935ffdbecbdb3
// flow-typed version: <<STUB>>/libqp_v^1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libqp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libqp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libqp/lib/libqp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libqp/lib/libqp.js' {
  declare module.exports: $Exports<'libqp/lib/libqp'>;
}
