// flow-typed signature: ca67020f31ac05404541fdbd0eb2ec03
// flow-typed version: <<STUB>>/mailparser_v^2.0.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailparser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailparser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailparser/lib/flowed-decoder' {
  declare module.exports: any;
}

declare module 'mailparser/lib/mail-parser' {
  declare module.exports: any;
}

declare module 'mailparser/lib/simple-parser' {
  declare module.exports: any;
}

declare module 'mailparser/lib/stream-hash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailparser/index' {
  declare module.exports: $Exports<'mailparser'>;
}
declare module 'mailparser/index.js' {
  declare module.exports: $Exports<'mailparser'>;
}
declare module 'mailparser/lib/flowed-decoder.js' {
  declare module.exports: $Exports<'mailparser/lib/flowed-decoder'>;
}
declare module 'mailparser/lib/mail-parser.js' {
  declare module.exports: $Exports<'mailparser/lib/mail-parser'>;
}
declare module 'mailparser/lib/simple-parser.js' {
  declare module.exports: $Exports<'mailparser/lib/simple-parser'>;
}
declare module 'mailparser/lib/stream-hash.js' {
  declare module.exports: $Exports<'mailparser/lib/stream-hash'>;
}
