// flow-typed signature: 04a605c46c464139705b136214516a27
// flow-typed version: <<STUB>>/pouchdb-node_v^6.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-node/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb-node/lib/index' {
  declare module.exports: any;
}

declare module 'pouchdb-node/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-node/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb-node/lib/index.es'>;
}
declare module 'pouchdb-node/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-node/lib/index'>;
}
declare module 'pouchdb-node/src/index.js' {
  declare module.exports: $Exports<'pouchdb-node/src/index'>;
}
