// flow-typed signature: 4ca372601ba98952c0bffdbe5ffd6285
// flow-typed version: <<STUB>>/pouchdb-find_v^0.10.5/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-find/bin/dev-server' {
  declare module.exports: any;
}

declare module 'pouchdb-find/bin/es3ify' {
  declare module.exports: any;
}

declare module 'pouchdb-find/bin/test-browser' {
  declare module.exports: any;
}

declare module 'pouchdb-find/dist/pouchdb.find' {
  declare module.exports: any;
}

declare module 'pouchdb-find/dist/pouchdb.find.min' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/abstract-mapreduce/create-view' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/abstract-mapreduce/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/abstract-mapreduce/taskqueue' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/abstract-mapreduce/upsert' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/abstract-mapreduce/utils' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/http/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/abstract-mapper' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/create-index/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/delete-index/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/find/in-memory-filter' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/find/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/find/query-planner' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/get-indexes/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/adapters/local/utils' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/deps/blob' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/deps/errors' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/deps/parse-uri' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/massageCreateIndexRequest' {
  declare module.exports: any;
}

declare module 'pouchdb-find/lib/utils' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/bind-polyfill' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/evalfunc' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/mapreduce' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/test.custom' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/test.mapreduce' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/test.persisted' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-abstract-mapreduce/utils' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.and' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.array' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.basic' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.basic2' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.basic3' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.callbacks' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.combinational' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.ddoc' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.deep-fields' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.default-index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.elem-match' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.eq' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.errors' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.exists' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.fields' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.issue66' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.limit-skip' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.limit' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.ltgt' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.matching-indexes' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.mod' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.ne' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.not' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.pick-fields' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.regex' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.set-operations' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.skip' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.sorting' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-1/test.type' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-2/index' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-2/test.kitchen-sink-2' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-suite-2/test.kitchen-sink' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test-utils' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/test' {
  declare module.exports: any;
}

declare module 'pouchdb-find/test/webrunner' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/ace/ace' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/ace/mode-javascript' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/ace/theme-xcode' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/ace/worker-javascript' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/app' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/bootstrap/js/bootstrap' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/bootstrap/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/bootstrap/js/npm' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/handlebars/handlebars-v2.0.0' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/handlebars/handlebars.runtime-v2.0.0' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/jquery/jquery.min' {
  declare module.exports: any;
}

declare module 'pouchdb-find/www/pouchdb-3.2.2-prerelease' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-find/bin/dev-server.js' {
  declare module.exports: $Exports<'pouchdb-find/bin/dev-server'>;
}
declare module 'pouchdb-find/bin/es3ify.js' {
  declare module.exports: $Exports<'pouchdb-find/bin/es3ify'>;
}
declare module 'pouchdb-find/bin/test-browser.js' {
  declare module.exports: $Exports<'pouchdb-find/bin/test-browser'>;
}
declare module 'pouchdb-find/dist/pouchdb.find.js' {
  declare module.exports: $Exports<'pouchdb-find/dist/pouchdb.find'>;
}
declare module 'pouchdb-find/dist/pouchdb.find.min.js' {
  declare module.exports: $Exports<'pouchdb-find/dist/pouchdb.find.min'>;
}
declare module 'pouchdb-find/lib/abstract-mapreduce/create-view.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/abstract-mapreduce/create-view'>;
}
declare module 'pouchdb-find/lib/abstract-mapreduce/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/abstract-mapreduce/index'>;
}
declare module 'pouchdb-find/lib/abstract-mapreduce/taskqueue.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/abstract-mapreduce/taskqueue'>;
}
declare module 'pouchdb-find/lib/abstract-mapreduce/upsert.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/abstract-mapreduce/upsert'>;
}
declare module 'pouchdb-find/lib/abstract-mapreduce/utils.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/abstract-mapreduce/utils'>;
}
declare module 'pouchdb-find/lib/adapters/http/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/http/index'>;
}
declare module 'pouchdb-find/lib/adapters/local/abstract-mapper.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/abstract-mapper'>;
}
declare module 'pouchdb-find/lib/adapters/local/create-index/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/create-index/index'>;
}
declare module 'pouchdb-find/lib/adapters/local/delete-index/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/delete-index/index'>;
}
declare module 'pouchdb-find/lib/adapters/local/find/in-memory-filter.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/find/in-memory-filter'>;
}
declare module 'pouchdb-find/lib/adapters/local/find/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/find/index'>;
}
declare module 'pouchdb-find/lib/adapters/local/find/query-planner.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/find/query-planner'>;
}
declare module 'pouchdb-find/lib/adapters/local/get-indexes/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/get-indexes/index'>;
}
declare module 'pouchdb-find/lib/adapters/local/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/index'>;
}
declare module 'pouchdb-find/lib/adapters/local/utils.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/adapters/local/utils'>;
}
declare module 'pouchdb-find/lib/deps/blob.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/deps/blob'>;
}
declare module 'pouchdb-find/lib/deps/errors.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/deps/errors'>;
}
declare module 'pouchdb-find/lib/deps/parse-uri.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/deps/parse-uri'>;
}
declare module 'pouchdb-find/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/index'>;
}
declare module 'pouchdb-find/lib/massageCreateIndexRequest.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/massageCreateIndexRequest'>;
}
declare module 'pouchdb-find/lib/utils.js' {
  declare module.exports: $Exports<'pouchdb-find/lib/utils'>;
}
declare module 'pouchdb-find/test/bind-polyfill.js' {
  declare module.exports: $Exports<'pouchdb-find/test/bind-polyfill'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/evalfunc.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/evalfunc'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/index.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/index'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/mapreduce.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/mapreduce'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/test.custom.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/test.custom'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/test.mapreduce.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/test.mapreduce'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/test.persisted.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/test.persisted'>;
}
declare module 'pouchdb-find/test/test-abstract-mapreduce/utils.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-abstract-mapreduce/utils'>;
}
declare module 'pouchdb-find/test/test-suite-1/index.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/index'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.and.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.and'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.array.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.array'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.basic.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.basic'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.basic2.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.basic2'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.basic3.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.basic3'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.callbacks.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.callbacks'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.combinational.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.combinational'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.ddoc.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.ddoc'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.deep-fields.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.deep-fields'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.default-index.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.default-index'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.elem-match.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.elem-match'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.eq.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.eq'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.errors.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.errors'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.exists.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.exists'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.fields.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.fields'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.issue66.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.issue66'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.limit-skip.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.limit-skip'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.limit.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.limit'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.ltgt.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.ltgt'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.matching-indexes.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.matching-indexes'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.mod.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.mod'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.ne.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.ne'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.not.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.not'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.pick-fields.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.pick-fields'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.regex.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.regex'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.set-operations.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.set-operations'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.skip.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.skip'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.sorting.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.sorting'>;
}
declare module 'pouchdb-find/test/test-suite-1/test.type.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-1/test.type'>;
}
declare module 'pouchdb-find/test/test-suite-2/index.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-2/index'>;
}
declare module 'pouchdb-find/test/test-suite-2/test.kitchen-sink-2.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-2/test.kitchen-sink-2'>;
}
declare module 'pouchdb-find/test/test-suite-2/test.kitchen-sink.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-suite-2/test.kitchen-sink'>;
}
declare module 'pouchdb-find/test/test-utils.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test-utils'>;
}
declare module 'pouchdb-find/test/test.js' {
  declare module.exports: $Exports<'pouchdb-find/test/test'>;
}
declare module 'pouchdb-find/test/webrunner.js' {
  declare module.exports: $Exports<'pouchdb-find/test/webrunner'>;
}
declare module 'pouchdb-find/www/ace/ace.js' {
  declare module.exports: $Exports<'pouchdb-find/www/ace/ace'>;
}
declare module 'pouchdb-find/www/ace/mode-javascript.js' {
  declare module.exports: $Exports<'pouchdb-find/www/ace/mode-javascript'>;
}
declare module 'pouchdb-find/www/ace/theme-xcode.js' {
  declare module.exports: $Exports<'pouchdb-find/www/ace/theme-xcode'>;
}
declare module 'pouchdb-find/www/ace/worker-javascript.js' {
  declare module.exports: $Exports<'pouchdb-find/www/ace/worker-javascript'>;
}
declare module 'pouchdb-find/www/app.js' {
  declare module.exports: $Exports<'pouchdb-find/www/app'>;
}
declare module 'pouchdb-find/www/bootstrap/js/bootstrap.js' {
  declare module.exports: $Exports<'pouchdb-find/www/bootstrap/js/bootstrap'>;
}
declare module 'pouchdb-find/www/bootstrap/js/bootstrap.min.js' {
  declare module.exports: $Exports<'pouchdb-find/www/bootstrap/js/bootstrap.min'>;
}
declare module 'pouchdb-find/www/bootstrap/js/npm.js' {
  declare module.exports: $Exports<'pouchdb-find/www/bootstrap/js/npm'>;
}
declare module 'pouchdb-find/www/handlebars/handlebars-v2.0.0.js' {
  declare module.exports: $Exports<'pouchdb-find/www/handlebars/handlebars-v2.0.0'>;
}
declare module 'pouchdb-find/www/handlebars/handlebars.runtime-v2.0.0.js' {
  declare module.exports: $Exports<'pouchdb-find/www/handlebars/handlebars.runtime-v2.0.0'>;
}
declare module 'pouchdb-find/www/jquery/jquery.min.js' {
  declare module.exports: $Exports<'pouchdb-find/www/jquery/jquery.min'>;
}
declare module 'pouchdb-find/www/pouchdb-3.2.2-prerelease.js' {
  declare module.exports: $Exports<'pouchdb-find/www/pouchdb-3.2.2-prerelease'>;
}
