// flow-typed signature: 6f35f7303373add7404ee4d5274012a5
// flow-typed version: <<STUB>>/process-nextick-args_v^1.0.7/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'process-nextick-args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'process-nextick-args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'process-nextick-args/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'process-nextick-args/index' {
  declare module.exports: $Exports<'process-nextick-args'>;
}
declare module 'process-nextick-args/index.js' {
  declare module.exports: $Exports<'process-nextick-args'>;
}
declare module 'process-nextick-args/test.js' {
  declare module.exports: $Exports<'process-nextick-args/test'>;
}
