// flow-typed signature: 4ec504a026d36a4d70a44c9c25e9d4a7
// flow-typed version: <<STUB>>/sanitize-filename_v^1.6.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize-filename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize-filename' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sanitize-filename/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sanitize-filename/index' {
  declare module.exports: $Exports<'sanitize-filename'>;
}
declare module 'sanitize-filename/index.js' {
  declare module.exports: $Exports<'sanitize-filename'>;
}
declare module 'sanitize-filename/test.js' {
  declare module.exports: $Exports<'sanitize-filename/test'>;
}
