// flow-typed signature: 143cbbe2abd1da41e376633072f5758e
// flow-typed version: <<STUB>>/stream-to-blob_v^1.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-to-blob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-to-blob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-to-blob/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-to-blob/index' {
  declare module.exports: $Exports<'stream-to-blob'>;
}
declare module 'stream-to-blob/index.js' {
  declare module.exports: $Exports<'stream-to-blob'>;
}
declare module 'stream-to-blob/test/basic.js' {
  declare module.exports: $Exports<'stream-to-blob/test/basic'>;
}
