// flow-typed signature: 09dbf39eb25dfbb5f4922bfcb64b0703
// flow-typed version: <<STUB>>/xoauth2_v^1.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xoauth2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'xoauth2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xoauth2/Gruntfile' {
  declare module.exports: any;
}

declare module 'xoauth2/src/xoauth2' {
  declare module.exports: any;
}

declare module 'xoauth2/test/server' {
  declare module.exports: any;
}

declare module 'xoauth2/test/xoauth2-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xoauth2/Gruntfile.js' {
  declare module.exports: $Exports<'xoauth2/Gruntfile'>;
}
declare module 'xoauth2/src/xoauth2.js' {
  declare module.exports: $Exports<'xoauth2/src/xoauth2'>;
}
declare module 'xoauth2/test/server.js' {
  declare module.exports: $Exports<'xoauth2/test/server'>;
}
declare module 'xoauth2/test/xoauth2-test.js' {
  declare module.exports: $Exports<'xoauth2/test/xoauth2-test'>;
}
