#!/bin/bash

set -e

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd "$ROOT_DIR"

# Workaround to be used until this change makes into an ava release:
# https://github.com/avajs/ava/pull/1778
sed -i 's/onFulfill?:/onFulfill:/' node_modules/ava/index.js.flow

# Create symlinks in node_modules/ for each package so that Flow can find
# libraries.
flow-mono create-symlinks packages/*/.flowconfig

# Create additional symlinks for peer dependencies
symlink_lib () {
  local library_name="$1"
  for p in packages/*/node_modules; do
    rm -f "$p/$library_name"
    ln -s -t "$p" "$ROOT_DIR/node_modules/$library_name"
  done
}
symlink_lib "kefir"
