// flow-typed signature: e0e60a576b0aad54f0cabac9ecb2f38a
// flow-typed version: <<STUB>>/activitystrea.ms_vhallettj/activitystrea.ms#fix/template-idempotency/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'activitystrea.ms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'activitystrea.ms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'activitystrea.ms/src/activitystreams' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/contextloader' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/environment' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/extcontext' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/interval/_model' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/interval/interval' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/jsonld' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/middle' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_activity' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_base' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_collection' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_collectionpage' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_languagevalue' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_link' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_object' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_orderedcollection' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_orderedcollectionpage' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_place' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_profile' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_question' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_relationship' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/_tombstone' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/models/models' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/reasoner' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/social/_common' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/social/_compoundpopulation' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/social/_everyone' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/social/_interested' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/social/_population' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/social/social' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/stream' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/src/utils' {
  declare module.exports: any;
}

declare module 'activitystrea.ms/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'activitystrea.ms/src/activitystreams.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/activitystreams'>;
}
declare module 'activitystrea.ms/src/contextloader.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/contextloader'>;
}
declare module 'activitystrea.ms/src/environment.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/environment'>;
}
declare module 'activitystrea.ms/src/extcontext.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/extcontext'>;
}
declare module 'activitystrea.ms/src/interval/_model.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/interval/_model'>;
}
declare module 'activitystrea.ms/src/interval/interval.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/interval/interval'>;
}
declare module 'activitystrea.ms/src/jsonld.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/jsonld'>;
}
declare module 'activitystrea.ms/src/middle.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/middle'>;
}
declare module 'activitystrea.ms/src/models/_activity.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_activity'>;
}
declare module 'activitystrea.ms/src/models/_base.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_base'>;
}
declare module 'activitystrea.ms/src/models/_collection.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_collection'>;
}
declare module 'activitystrea.ms/src/models/_collectionpage.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_collectionpage'>;
}
declare module 'activitystrea.ms/src/models/_languagevalue.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_languagevalue'>;
}
declare module 'activitystrea.ms/src/models/_link.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_link'>;
}
declare module 'activitystrea.ms/src/models/_object.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_object'>;
}
declare module 'activitystrea.ms/src/models/_orderedcollection.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_orderedcollection'>;
}
declare module 'activitystrea.ms/src/models/_orderedcollectionpage.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_orderedcollectionpage'>;
}
declare module 'activitystrea.ms/src/models/_place.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_place'>;
}
declare module 'activitystrea.ms/src/models/_profile.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_profile'>;
}
declare module 'activitystrea.ms/src/models/_question.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_question'>;
}
declare module 'activitystrea.ms/src/models/_relationship.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_relationship'>;
}
declare module 'activitystrea.ms/src/models/_tombstone.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/_tombstone'>;
}
declare module 'activitystrea.ms/src/models/models.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/models/models'>;
}
declare module 'activitystrea.ms/src/reasoner.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/reasoner'>;
}
declare module 'activitystrea.ms/src/social/_common.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/social/_common'>;
}
declare module 'activitystrea.ms/src/social/_compoundpopulation.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/social/_compoundpopulation'>;
}
declare module 'activitystrea.ms/src/social/_everyone.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/social/_everyone'>;
}
declare module 'activitystrea.ms/src/social/_interested.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/social/_interested'>;
}
declare module 'activitystrea.ms/src/social/_population.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/social/_population'>;
}
declare module 'activitystrea.ms/src/social/social.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/social/social'>;
}
declare module 'activitystrea.ms/src/stream.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/stream'>;
}
declare module 'activitystrea.ms/src/utils.js' {
  declare module.exports: $Exports<'activitystrea.ms/src/utils'>;
}
declare module 'activitystrea.ms/test/test.js' {
  declare module.exports: $Exports<'activitystrea.ms/test/test'>;
}
