// flow-typed signature: ef5532a43513f54f2f025e1fd4d232bd
// flow-typed version: <<STUB>>/activitystreams-context_v^1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'activitystreams-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'activitystreams-context' {
  declare module.exports: any;
}
