// flow-typed signature: fb35aa7b4ea8682121493105b416f54d
// flow-typed version: <<STUB>>/activitystreams-context_v^1.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'activitystreams-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'activitystreams-context' {
  declare module.exports: any;
}
