// flow-typed signature: 23f1753746f432d16ace3c82fcac2c52
// flow-typed version: <<STUB>>/buildmail_v^4.0.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buildmail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buildmail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buildmail/Gruntfile' {
  declare module.exports: any;
}

declare module 'buildmail/lib/buildmail' {
  declare module.exports: any;
}

declare module 'buildmail/test/libbuildmail-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buildmail/Gruntfile.js' {
  declare module.exports: $Exports<'buildmail/Gruntfile'>;
}
declare module 'buildmail/lib/buildmail.js' {
  declare module.exports: $Exports<'buildmail/lib/buildmail'>;
}
declare module 'buildmail/test/libbuildmail-test.js' {
  declare module.exports: $Exports<'buildmail/test/libbuildmail-test'>;
}
