// flow-typed signature: c52d11621a66858871d688bc47098db3
// flow-typed version: <<STUB>>/email-addresses_v^2.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'email-addresses'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'email-addresses' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'email-addresses/lib/email-addresses' {
  declare module.exports: any;
}

declare module 'email-addresses/test/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'email-addresses/lib/email-addresses.js' {
  declare module.exports: $Exports<'email-addresses/lib/email-addresses'>;
}
declare module 'email-addresses/test/run.js' {
  declare module.exports: $Exports<'email-addresses/test/run'>;
}
