// flow-typed signature: d4a73717861f101eaa9394227be5fc55
// flow-typed version: <<STUB>>/email-addresses_v^3.0.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'email-addresses'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'email-addresses' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'email-addresses/lib/email-addresses' {
  declare module.exports: any;
}

declare module 'email-addresses/lib/email-addresses.min' {
  declare module.exports: any;
}

declare module 'email-addresses/test/email-addresses' {
  declare module.exports: any;
}

declare module 'email-addresses/test/is_email' {
  declare module.exports: any;
}

// Filename aliases
declare module 'email-addresses/lib/email-addresses.js' {
  declare module.exports: $Exports<'email-addresses/lib/email-addresses'>;
}
declare module 'email-addresses/lib/email-addresses.min.js' {
  declare module.exports: $Exports<'email-addresses/lib/email-addresses.min'>;
}
declare module 'email-addresses/test/email-addresses.js' {
  declare module.exports: $Exports<'email-addresses/test/email-addresses'>;
}
declare module 'email-addresses/test/is_email.js' {
  declare module.exports: $Exports<'email-addresses/test/is_email'>;
}
