// flow-typed signature: 41306750783d05720015bcc640078685
// flow-typed version: <<STUB>>/libmime_v^3.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libmime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libmime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libmime/lib/charset' {
  declare module.exports: any;
}

declare module 'libmime/lib/charsets' {
  declare module.exports: any;
}

declare module 'libmime/lib/libmime' {
  declare module.exports: any;
}

declare module 'libmime/lib/mimetypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libmime/lib/charset.js' {
  declare module.exports: $Exports<'libmime/lib/charset'>;
}
declare module 'libmime/lib/charsets.js' {
  declare module.exports: $Exports<'libmime/lib/charsets'>;
}
declare module 'libmime/lib/libmime.js' {
  declare module.exports: $Exports<'libmime/lib/libmime'>;
}
declare module 'libmime/lib/mimetypes.js' {
  declare module.exports: $Exports<'libmime/lib/mimetypes'>;
}
