// flow-typed signature: a30547adb754da4d730da8ee9ea23d16
// flow-typed version: <<STUB>>/media-type_v^0.3.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'media-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'media-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'media-type/lib/mediaType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'media-type/lib/mediaType.js' {
  declare module.exports: $Exports<'media-type/lib/mediaType'>;
}
