// flow-typed signature: 64b2714acf3d21d5559f306301598e7b
// flow-typed version: <<STUB>>/stream-to-string_v^1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-to-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-to-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-to-string/example/promise' {
  declare module.exports: any;
}

declare module 'stream-to-string/example/usage' {
  declare module.exports: any;
}

declare module 'stream-to-string/test/enc' {
  declare module.exports: any;
}

declare module 'stream-to-string/test/error' {
  declare module.exports: any;
}

declare module 'stream-to-string/test/promise' {
  declare module.exports: any;
}

declare module 'stream-to-string/test/value' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-to-string/example/promise.js' {
  declare module.exports: $Exports<'stream-to-string/example/promise'>;
}
declare module 'stream-to-string/example/usage.js' {
  declare module.exports: $Exports<'stream-to-string/example/usage'>;
}
declare module 'stream-to-string/index' {
  declare module.exports: $Exports<'stream-to-string'>;
}
declare module 'stream-to-string/index.js' {
  declare module.exports: $Exports<'stream-to-string'>;
}
declare module 'stream-to-string/test/enc.js' {
  declare module.exports: $Exports<'stream-to-string/test/enc'>;
}
declare module 'stream-to-string/test/error.js' {
  declare module.exports: $Exports<'stream-to-string/test/error'>;
}
declare module 'stream-to-string/test/promise.js' {
  declare module.exports: $Exports<'stream-to-string/test/promise'>;
}
declare module 'stream-to-string/test/value.js' {
  declare module.exports: $Exports<'stream-to-string/test/value'>;
}
