// flow-typed signature: 9fd01a70c9f9e59cffca3f4fc99a9e0c
// flow-typed version: <<STUB>>/stream-from-promise_v^1.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-from-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-from-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stream-from-promise/index' {
  declare module.exports: $Exports<'stream-from-promise'>;
}
declare module 'stream-from-promise/index.js' {
  declare module.exports: $Exports<'stream-from-promise'>;
}
