// flow-typed signature: bbab3ce6fc811dac6811c80ea9b3170c
// flow-typed version: <<STUB>>/traverse_v^0.6.6/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'traverse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'traverse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'traverse/examples/json' {
  declare module.exports: any;
}

declare module 'traverse/examples/leaves' {
  declare module.exports: any;
}

declare module 'traverse/examples/negative' {
  declare module.exports: any;
}

declare module 'traverse/examples/scrub' {
  declare module.exports: any;
}

declare module 'traverse/examples/stringify' {
  declare module.exports: any;
}

declare module 'traverse/test/circular' {
  declare module.exports: any;
}

declare module 'traverse/test/date' {
  declare module.exports: any;
}

declare module 'traverse/test/equal' {
  declare module.exports: any;
}

declare module 'traverse/test/error' {
  declare module.exports: any;
}

declare module 'traverse/test/has' {
  declare module.exports: any;
}

declare module 'traverse/test/instance' {
  declare module.exports: any;
}

declare module 'traverse/test/interface' {
  declare module.exports: any;
}

declare module 'traverse/test/json' {
  declare module.exports: any;
}

declare module 'traverse/test/keys' {
  declare module.exports: any;
}

declare module 'traverse/test/leaves' {
  declare module.exports: any;
}

declare module 'traverse/test/lib/deep_equal' {
  declare module.exports: any;
}

declare module 'traverse/test/mutability' {
  declare module.exports: any;
}

declare module 'traverse/test/negative' {
  declare module.exports: any;
}

declare module 'traverse/test/obj' {
  declare module.exports: any;
}

declare module 'traverse/test/siblings' {
  declare module.exports: any;
}

declare module 'traverse/test/stop' {
  declare module.exports: any;
}

declare module 'traverse/test/stringify' {
  declare module.exports: any;
}

declare module 'traverse/test/subexpr' {
  declare module.exports: any;
}

declare module 'traverse/test/super_deep' {
  declare module.exports: any;
}

declare module 'traverse/testling/leaves' {
  declare module.exports: any;
}

// Filename aliases
declare module 'traverse/examples/json.js' {
  declare module.exports: $Exports<'traverse/examples/json'>;
}
declare module 'traverse/examples/leaves.js' {
  declare module.exports: $Exports<'traverse/examples/leaves'>;
}
declare module 'traverse/examples/negative.js' {
  declare module.exports: $Exports<'traverse/examples/negative'>;
}
declare module 'traverse/examples/scrub.js' {
  declare module.exports: $Exports<'traverse/examples/scrub'>;
}
declare module 'traverse/examples/stringify.js' {
  declare module.exports: $Exports<'traverse/examples/stringify'>;
}
declare module 'traverse/index' {
  declare module.exports: $Exports<'traverse'>;
}
declare module 'traverse/index.js' {
  declare module.exports: $Exports<'traverse'>;
}
declare module 'traverse/test/circular.js' {
  declare module.exports: $Exports<'traverse/test/circular'>;
}
declare module 'traverse/test/date.js' {
  declare module.exports: $Exports<'traverse/test/date'>;
}
declare module 'traverse/test/equal.js' {
  declare module.exports: $Exports<'traverse/test/equal'>;
}
declare module 'traverse/test/error.js' {
  declare module.exports: $Exports<'traverse/test/error'>;
}
declare module 'traverse/test/has.js' {
  declare module.exports: $Exports<'traverse/test/has'>;
}
declare module 'traverse/test/instance.js' {
  declare module.exports: $Exports<'traverse/test/instance'>;
}
declare module 'traverse/test/interface.js' {
  declare module.exports: $Exports<'traverse/test/interface'>;
}
declare module 'traverse/test/json.js' {
  declare module.exports: $Exports<'traverse/test/json'>;
}
declare module 'traverse/test/keys.js' {
  declare module.exports: $Exports<'traverse/test/keys'>;
}
declare module 'traverse/test/leaves.js' {
  declare module.exports: $Exports<'traverse/test/leaves'>;
}
declare module 'traverse/test/lib/deep_equal.js' {
  declare module.exports: $Exports<'traverse/test/lib/deep_equal'>;
}
declare module 'traverse/test/mutability.js' {
  declare module.exports: $Exports<'traverse/test/mutability'>;
}
declare module 'traverse/test/negative.js' {
  declare module.exports: $Exports<'traverse/test/negative'>;
}
declare module 'traverse/test/obj.js' {
  declare module.exports: $Exports<'traverse/test/obj'>;
}
declare module 'traverse/test/siblings.js' {
  declare module.exports: $Exports<'traverse/test/siblings'>;
}
declare module 'traverse/test/stop.js' {
  declare module.exports: $Exports<'traverse/test/stop'>;
}
declare module 'traverse/test/stringify.js' {
  declare module.exports: $Exports<'traverse/test/stringify'>;
}
declare module 'traverse/test/subexpr.js' {
  declare module.exports: $Exports<'traverse/test/subexpr'>;
}
declare module 'traverse/test/super_deep.js' {
  declare module.exports: $Exports<'traverse/test/super_deep'>;
}
declare module 'traverse/testling/leaves.js' {
  declare module.exports: $Exports<'traverse/testling/leaves'>;
}
